
export enum ACCOUNTSTATUS{
    APPROVAL_PENDING = "APPROVAL_PENDING",
    ACTIVE  = "ACTIVE",
    INACTIVE = "INACTIVE",
    BLOCKED  =  "BLOCKED",
    DELETED  = "DELETED"
}

export enum ACCOUNTTYPE{
    STUDENT  =  "STUDENT",
    EMPLOYER  = "EMPLOYER"
}